#ifndef VERSION_HPP
#define VERSION_HPP

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 1
#define APP_VERSION_PATCH 0

#define APP_VERSION_STRING                        \
    "v" TOSTRING(APP_VERSION_MAJOR) "." TOSTRING( \
        APP_VERSION_MINOR) "." TOSTRING(APP_VERSION_PATCH)
#endif  // VERSION_HPP
